### ISSUE TITLE
"String data, right truncation" error from parse_drug(TRUE)

### ISSUE THREAD

**Issue by sharmb** [Dainanahan/dbparser#56] opened 2019-08-08 21:33 UTC
While trying to save "drugs" dataframe into SQL database, a "String data, right truncation" error is returned, with the following: 

`open_db(driver="SQL Server", server="servername", output_database="databasename")`
`parse_drug(TRUE)`

`Error in result_insert_dataframe(rs@ptr, values) : 
       [Microsoft][ODBC SQL Server Driver]String data, right truncation`

(xml_db_name parameter was removed from open_db after an "unused argument" error was returned due to it)

**Comment by MohammedFCIS** [comment] 2019-08-09 17:26
Hi @sharmb what DrugBank db version you are using? this happened when the parsed column is bigger than the default size of SQL server. It seems I need to make it a little bigger, hence; I need to know the DrugBank version.
Thank you

**Comment by sharmb** [comment] 2019-08-10 19:10
I am using Version 5.1.4 of Drugbank. 

Thank you!

**Comment by MohammedFCIS** [comment] 2019-08-18 13:06
@sharmb - The issue is fixed now, you can install the dev version from dbparser until the fix is officially released by the end of this month. You can also use the latest parsed framework from drugbank here https://dainanahan.github.io/dbdataset/articles/dbdataset.html.
Thank you for your contributions and using dbparser :).

**Closed by MohammedFCIS** 2019-08-18 13:06 UTC
Labels: good first issue
